name: Test on PR

on:
  pull_request:
    synchronize:

jobs:
  nginx:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: list
        run: ls -la
      - name: validate json files.
        id: json-validation
        working-directory: ./tools/validator
        run: ls -la
