name: Test on PR

on:
  pull_request:
    synchronize:

jobs:
  nginx:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: validate json files.
        id: json-validation
        working-directory: /home/runner/work/regions/tools/validator
        run: ./mvnw test
